version: "3.7"
services:
  php:
    build:
      context: .
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - .:/var/www:cached
      -  ./docker/php/custom.ini:/usr/local/etc/php/conf.d/zzz_custom.ini:cached
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - .:/var/www:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./logs/nginx:/var/log/nginx:delegated
    depends_on:
      - php
